### ISSUE TITLE
Error: invalid immediate value [object Object]

### ISSUE THREAD

**Issue by rocketana** [koskimas/kysely#343]
When I have `col.defaultTo(sql'now()')` in a migration, applying it raises the error `Error: invalid immediate value [object Object]`:

```
 Error: invalid immediate value [object Object]
    at PostgresDataApiQueryCompiler.appendImmediateValue (file:///.../node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:934:19)
    at PostgresDataApiQueryCompiler.visitValue (file:///.../node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:266:18)
    at PostgresDataApiQueryCompiler.visitNode (file:///.../node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.visitDefaultValue (file:///.../node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:824:14)
    at PostgresDataApiQueryCompiler.visitNode (file:///.../node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.visitColumnDefinition (file:///.../node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:367:18)
    at PostgresDataApiQueryCompiler.visitNode (file:///.../node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
    at PostgresDataApiQueryCompiler.compileList (file:///.../node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:116:18)
    at PostgresDataApiQueryCompiler.visitCreateTable (file:///.../node_modules/kysely/dist/esm/query-compiler/default-query-compiler.js:343:14)
    at PostgresDataApiQueryCompiler.visitNode (file:///.../node_modules/kysely/dist/esm/operation-node/operation-node-visitor.js:84:34)
```

I'm using `kysely-data-api` (for AWS RDS). Here's the DB setup:

```
import { Kysely, Selectable } from "kysely";
import { DataApiDialect } from "kysely-data-api";
import RDSDataService from "aws-sdk/clients/rdsdataservice";
import { RDS } from "sst/node/rds";

const dataApi = new DataApiDialect({
    mode: "postgres",
    driver: {
        secretArn: (RDS as any).db.secretArn,
        resourceArn: (RDS as any).db.clusterArn,
        database: (RDS as any).db.defaultDatabaseName,
        client: new RDSDataService(),
    },
}) as any;

export const DB = new Kysely<Database>({
    dialect: dataApi
});

export type Row = {
    [Key in keyof Database]: Selectable<Database[Key]>;
};
```

Sample migration (which executed fine if I remove `sql'now()'`):
```
export async function up(db) {
    await db.schema
        .createTable("entry")
        .addColumn("id", "text", (col) => col.primaryKey())
        .addColumn("title", "text", (col) => col.notNull())
        .addColumn("created", "timestamp", (col) => col.defaultTo(sql`now()`).notNull())
        .execute();
}
```

**Comment by koskimas** [comment]
You have two versions of kysely. The `sql` tag comes from one, and the dialect that's trying to parse it comes from another one that's incompatible.

Ultimately this is a configuration issue and you should make sure you only use one copy of kysely. But that is often difficult and for that reason the latest versions of kysely have workarounds for this.

Your options:

1. Update all kyselys in your project to latest version.
2. Make sure you only use one version

**Comment by koskimas** [comment]
You can use something like this to find the different versions:

```sh
find node_modules -name "kysely.js"
```

**Comment by Jazcash** [comment]
I'm also getting this issue since adding a package (my own) that uses kysely, as well as my main project having it already. However, both are on version 0.25.0 and I have `$kysely` set in `overrides` in my `package.json`.
