### ISSUE TITLE
Error stack doesn't include userspace details

### ISSUE THREAD

**Issue by ejose19** [koskimas/kysely#79]
Given the following file:

```ts
// src/index.ts
import { Kysely, sql, SqliteDialect } from "kysely";

const db = new Kysely({
  dialect: new SqliteDialect({
    databasePath: ":memory:",
  }),
});

(async () => {
  console.log(await sql`select 1a`.execute(db));
})();
```

it errors out with:
```
/home/user/test/node_modules/better-sqlite3/lib/methods/wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                    ^
SqliteError: unrecognized token: "1a"
    at Database.prepare (/home/user/test/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at SqliteConnection.executeQuery (/home/user/test/node_modules/kysely/dist/cjs/dialect/sqlite/sqlite-driver.js:87:31)
    at /home/user/test/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:35:45
    at DefaultConnectionProvider.provideConnection (/home/user/test/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:26)
    at async DefaultQueryExecutor.executeQuery (/home/user/test/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:34:16) {
  code: 'SQLITE_ERROR'
}
```

however, thrown error doesn't include any references to the "user file" (src/index.ts), which makes debugging difficult

## Additional info

If the call is done with the db driver alone, stack details show correctly

```ts
import Database from "better-sqlite3";

(async () => {
  const db = new Database(":memory:");

  console.log(db.exec(`select 1a`));
})();
```

```
/home/user/test/node_modules/better-sqlite3/lib/methods/wrappers.js:9
        this[cppdb].exec(sql);
             ^
SqliteError: unrecognized token: "1a"
    at Database.exec (/home/user/test/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at /home/user/test/src/index.ts:18:18
    at Generator.next (<anonymous>)
    at /home/user/test/src/index.ts:9:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/test/src/index.ts:5:12)
    at /home/user/test/src/index.ts:15:13
    at Object.<anonymous> (/home/user/test/src/index.ts:19:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module.m._compile (/home/user/test/node_modules/ts-node/src/index.ts:1455:23) {
  code: 'SQLITE_ERROR'
}
```

**Comment by koskimas** [comment]
This is a common problem with async code. As soon as you do something other than `await func()` with promises, the stack trace gets cut. Kysely has a bunch of places that use promises in a more advanced way. Fixing this, and more importantly keeping this working, is difficult.

Also the sqlite client seems to be the only one that even produces errors that keep their stack trace. Here are the errors produced by mysql and postgres:

```
error: column "doesntexists" does not exist
    at Parser.parseErrorMessage (/Users/foo/Projects/kysely/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/foo/Projects/kysely/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/foo/Projects/kysely/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/foo/Projects/kysely/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

Error: Unknown column 'doesntexists' in 'field list'
    at Packet.asError (/Users/foo/Projects/kysely/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/foo/Projects/kysely/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/foo/Projects/kysely/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/foo/Projects/kysely/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/foo/Projects/kysely/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/foo/Projects/kysely/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by koskimas** [comment]
We could add something like this to `query-executor-base.ts`

```ts
  async executeQuery<R>(
    compiledQuery: CompiledQuery,
    queryId: QueryId
  ): Promise<QueryResult<R>> {
    try {
      return await this.provideConnection(async (connection) => {
        const result = await connection.executeQuery(compiledQuery)
        return this.#transformResult(result, queryId)
      })
    } catch (err: any) {
      const stack: { stack: string } = { stack: '' }
      Error.captureStackTrace(stack)
      err.stack += `\n${stack.stack.split('\n').slice(1).join('\n')}`
      throw err
    }
  }
 ```

Would that be enough?

**Comment by koskimas** [comment]
I implemented the solution above. It doesn't preserve the whole stack trace, but it does show the userspace stack in addition to the currently visible stack. There's a piece missing in between though, but I don't think that part contains anything useful for the users. Please check out the commit and  let me know if this works well enough.

**Comment by ejose19** [comment]
Something of interest, I bumped `target` to `ES2017` and I'm getting this in the stack with `kysely@0.18.0`:

```
/home/user/test/node_modules/better-sqlite3/lib/methods/wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                    ^
SqliteError: unrecognized token: "1a"
    at Database.prepare (/home/user/test/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at SqliteConnection.executeQuery (/home/user/test/node_modules/kysely/dist/cjs/dialect/sqlite/sqlite-driver.js:87:31)
    at /home/user/test/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:35:45
    at DefaultConnectionProvider.provideConnection (/home/user/test/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:26)
    at async DefaultQueryExecutor.executeQuery (/home/user/test/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:34:16)
    at async /home/user/test/src/index.ts:10:15 {
  code: 'SQLITE_ERROR'
}
```

using anything lower and the `at async /home/user/test/src/index.ts:10:15` line doesn't show up anymore (even with your latest commit)

Now, after applying that commit I see the source line showing up as a duplicate:

```
/home/user/test/node_modules/kysely/node_modules/better-sqlite3/lib/methods/wrappers.js:5
        return this[cppdb].prepare(sql, this, false);

SqliteError: unrecognized token: "1a"
    at Database.prepare (/home/user/test/node_modules/kysely/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at SqliteConnection.executeQuery (/home/user/test/node_modules/kysely/dist/cjs/dialect/sqlite/sqlite-driver.js:87:31)
    at /home/user/test/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:36:49
    at DefaultConnectionProvider.provideConnection (/home/user/test/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:26)
    at async DefaultQueryExecutor.executeQuery (/home/user/test/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:35:20)
    at async /home/user/test/src/index.ts:10:15
    at extendStackTrace (/home/user/test/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:60:28)
    at DefaultQueryExecutor.executeQuery (/home/user/test/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:44:19)
    at async /home/user/test/src/index.ts:10:15 {
  code: 'SQLITE_ERROR'
}
```

so I wonder if the fix is being redundant @ `target >= ES2017`?

Btw, I think that if the error header shown the user code instead of `better-sqlite3` one, it would be more helpful to the user, something like this:

```
/home/user/test/src/index.ts:10:15
    console.log(await sql`select 1a`.execute(db));
                ^
```

I will investigate if there's a way to do that

**Comment by koskimas** [comment]
Yeah I assumed you were transpiling away the async/await code since I got the full stack trace on sqlite. I don't think it's worth it to remove the duplicate. It doesn't make the debugging experience any worse. It's just a little weird, but you get the information anyway. It only matters if you are figuring out what kysely is doing internally. In that case it might mislead you to think there's some kind of recursive call there.

**Comment by koskimas** [comment]
When you investigate and test out stuff, please do it with all supported dialects. They all behave differently in this case.

**Comment by ejose19** [comment]
Just tried your latest commit with `postgres` and `mysql`, and for these user stack line only shows up once, with no line showing up on `kysely@0.18.0`, so the fix is working properly.

Given the sync nature for `sqlite`, should we exclude it from the fix? After all, it just adds extra information with no apparent usefulness

> The solution is to keep async/await since it's been around about 5 years now

Yes, I was just testing with default `tsc --init`, I usually work with newest targets

**Comment by koskimas** [comment]
We can't create a dependency to `better-sqlite3` there or everyone needs to install it. So instanceof is out of the question. Comparing the error name is error-prone. Either way, the internals of Kysely should not depend or even know about the specific dialects. They should just work with the abstract interfaces.

**Comment by ejose19** [comment]
In that case, only solution I could think of is adding another method to `DialectAdapterBase`, like `requiresExtendingStackTrace` (name could be better), then calling like this:

```ts
} catch (err) {
  if (!this.adapter.requiresExtendingStackTrace()) {
    throw err
  }

  // The async stack trace gets cut because of all the Promise magic
  ...
```

what do you think?

**Comment by koskimas** [comment]
I don't think we should do that either. It's one more thing people need to implement when they create a dialect.

We could just check if `__filename` exists in the stack and skip extending in that case.

**Comment by koskimas** [comment]
I moved the extension code to a helper and now call if inside the drivers that need extending.

**Comment by ejose19** [comment]
Ok, that is a better solution. Sadly seems like just appending to the stack is not enough, as some libraries extract the stack from stored call sites (by setting a custom `Error.prepareStackTrace`), an example of this is `tslog` library, where the logged error only shows the original stack and not the appended info in this PR.

I was thinking on some alternatives, first one is using `Error.cause`, which would be the "clean" way to do it as we want to merge 2 stacks.

```ts
return new Error('DatabaseError', { cause: err });
```

Second alternative would be merging the original error into the one created for `extendStackTrace`, however the original error stack will be lost (although given the `emit` nature of postgres & mysql drivers, these stacks are basically useless)

```ts
Object.assign(stackError, err);
stackError.message = err.message;
return stackError;
```

First one is ideal, but I don't know if the current support for that feature matches `kysely` one, at worst we could fallback to current implementation or 2nd alternative

**Comment by koskimas** [comment]
We can't do either of those or we break the underlying errors. Instanceof etc no longer work.
